### ISSUE TITLE
Possible typo in ledge handling in ProbeGround

### ISSUE THREAD

**Issue by hinshun** [IronWarrior/SuperCharacterController#16]
I was going through the SuperCharacterController line by line and noticed this possible typo:

https://github.com/IronWarrior/SuperCharacterController/blob/master/Assets/SuperCharacterController/Core/SuperCharacterController.cs#L653

A few lines before that, a SuperCollisionType was retrieved and stored in variable `col`, but it is never used. Instead `superColType`'s StandAngle is used to retrieve proper landing.

I believe we want to get the nearHit SuperCollisionType stand angle?

**Comment by IronWarrior** [comment]
You are correct. Most the time the two would share the same SuperCollisionType, as it's typical that in this case (when the controller is on the ledge) the wall of the ledge and the platform would be the same collider. However! Some of the research I've been doing a bit lately shows that some games actually split their walls/floors/ceilings in to distinct groups that are tested against independently (which would make grounding much easier), so I could see this error cropping up for some people. Good catch!
