### ISSUE TITLE
Scene contains nothing in Unity4.7.0

### ISSUE THREAD

**Issue by terrynoya** [IronWarrior/SuperCharacterController#18]
Hi,
I downloaded this project and open in Unity 4.7.0
All the Scene contain nothing,Which Unity Editor Version should I use?Please help.
Thanks you

**Comment by IronWarrior** [comment]
Unity 5.x. I did write some of the core scripts with 4.x so if you just use the scripts themselves I suspect they'd work, but the demo project is 5.x.

**Comment by terrynoya** [comment]
OK,thank you!
