### ISSUE TITLE
Rotation of collision spheres

### ISSUE THREAD

**Issue by hinshun** [IronWarrior/SuperCharacterController#19]
Since ground probing occurs from the feet sphere, how did you handle player rotations like a back flip? Do the collision spheres remain in the standing idle position? What about crouching?

**Comment by IronWarrior** [comment]
CollisionSpheres usually are only rotated if you want the character's physics and logic to be rotated. For backflips, you'd want to play an animation while leaving the spheres where they are. For crouching you can set the heightScale property.
