### ISSUE TITLE
Parenting to object

### ISSUE THREAD

**Issue by woistjadefox** [IronWarrior/SuperCharacterController#21]
Hi there! When I parent an SCC character to an object that moves, it applies the speed of the platform twice to the character.

I actually need to apply the force of the moving platform to the character when he jumps, otherwise it looks wrong because the platform moves away in the time the character is in the air. 

is there a way to deactivate the moving platform feature or do you have any idea how to fix this behavior?

**Comment by IronWarrior** [comment]
Hey, I added an option to disable clamping to moving platforms, a bool named clampToMovingGround. It's been pushed to master.
